on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [4.08.1, 4.09.1, 4.10.2, 4.11.2, 4.12.1, 4.13.1, 4.14.0]
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo...
        uses: actions/checkout@v2
      - name: recovering cached opam files...
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml-${{ matrix.ocaml-version }}
      - name: setting up opam...
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: installing dependencies...
        run: |
          opam repository add lambdapi https://github.com/deducteam/opam-lambdapi-repository.git
          opam update
          opam pin -n --dev-repo lambdapi
          opam pin -n --dev-repo lambdapi-logic
          opam upgrade
          opam pin add -n -k path skonverto .
          opam install --deps-only -d -t skonverto
      - name: compiling...
        run: |
          eval $(opam env)
          make
          make install
      - name: testing...
        run: |
          eval $(opam env)
          skonverto --signature signature --package skolem example/proof_skolem.lp
          lambdapi check example/proof_skolem_deskolemized.lp
